config/routes.rb
=> controllers, models, routes

app/controllers/users_controller.rb, app/views/chats/index.html.erb, config/initializers/devise.rb
adding sign up and log in buttons into index page
=> pushing sign up features

Gemfile, Gemfile.lock, app/controllers/users_controller.rb, db/migrate/20241126133247_add_chat_description_to_chats.rb, db/schema.rb, db/seeds.rb
Now we can seed users and chats.
=> add seed file and add description colum to chat table

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_list_chats.scss, app/controllers/chats_controller.rb, app/controllers/messages_controller.rb, app/views/chats/_form.html.erb, app/views/chats/list.html.erb, app/views/chats/new.html.erb, db/schema.rb
new chat function created
list page organized for mobile version
list page created
=> Listing chats

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_chat.scss, app/assets/stylesheets/components/_index.scss, app/controllers/chats_controller.rb, app/controllers/messages_controller.rb, app/javascript/controllers/reset_form_controller.js, app/models/chat.rb, app/models/message.rb, app/views/chats/list.html.erb, app/views/chats/list_by_user.html.erb, app/views/chats/show.html.erb, app/views/messages/_message.html.erb, config/cable.yml, config/routes.rb, db/cable_schema.rb, db/migrate/20241127120645_install_solid_queue.rb, db/schema.rb
=> add chat feature

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_app_general.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/views/chats/list.html.erb, app/views/chats/new.html.erb, app/views/layouts/application.html.erb
styling added to create group form
=> create group form styled

app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/users/show.html.erb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20241128134136_create_active_storage_tables.active_storage.rb, db/schema.rb
cloudinary gem added to user avatar
=> Cloudinary

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_searchbar.scss, app/assets/stylesheets/components/_user_card.scss, app/views/chats/list.html.erb, app/views/shared/_searchbar.html.erb, app/views/users/show.html.erb, db/schema.rb
=> profile stlye added

app/assets/stylesheets/components/_searchbar.scss, app/javascript/search_bar.js, app/views/layouts/application.html.erb, app/views/shared/_searchbar.html.erb
hide searchbar, display on click
=> searchbar styling

app/controllers/chats_controller.rb, app/controllers/joined_chats_controller.rb, app/javascript/controllers/join_button_controller.js, app/javascript/join.js, app/models/chat.rb, app/models/joined_chat.rb, app/models/user.rb, app/views/chats/_join.html.erb, app/views/chats/show.html.erb, config/routes.rb, db/migrate/20241202084100_create_joined_chats.rb, db/schema.rb, test/controllers/joined_chats_controller_test.rb, test/models/joined_chat_test.rb
=> Join button

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_join.scss, app/controllers/joined_chats_controller.rb, app/javascript/controllers/join_button_controller.js, app/javascript/join.js, app/models/chat.rb
=> join button styled

app/assets/stylesheets/components/_app_general.scss, app/controllers/chats_controller.rb, app/views/chats/list.html.erb, app/views/chats/list_by_user.html.erb, app/views/layouts/application.html.erb
divided my chats in tabs: created/joined
added create chat button
=> added chats tabs

app/assets/stylesheets/components/_app_general.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_list_by_user.scss, app/assets/stylesheets/components/_searchbar.scss, app/views/chats/list.html.erb, app/views/chats/list_by_user.html.erb
=> styled my chats

app/assets/stylesheets/components/_list_by_user.scss, app/assets/stylesheets/components/_message_card.scss, app/assets/stylesheets/components/_searchbar.scss, app/views/chats/list.html.erb, app/views/chats/list_by_user.html.erb
styling details to searchbar, your chats page, chat list page
=> styling details

app/views/chats/show.html.erb, app/views/stareds/_stared_failed.html.erb, app/views/stareds/index.html.erb, app/views/users/show.html.erb
=> favorites page information

app/assets/stylesheets/components/_app_general.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_message_card.scss, app/assets/stylesheets/components/_starred_card.scss, app/assets/stylesheets/components/_user_card.scss, app/views/stareds/index.html.erb
styling to favorite messages page
=> favorite page style

app/views/chats/new.html.erb
back button added to create new chat page
=> back button added to create chat page

app/assets/stylesheets/components/_chat_textbox.scss, app/assets/stylesheets/components/_index.scss
styled the text box for the chats, and the send button
=> textbox chat style

app/assets/stylesheets/components/_chat_textbox.scss, app/views/shared/_searchbar.html.erb
fixed class on searchbar that was taking style from message box
=> Searchbar fix

app/views/chats/list_by_user.html.erb
=> created chats online

app/assets/stylesheets/components/_searchbar.scss, app/views/chats/list_by_user.html.erb
made searchbar wider, removed borders from my chats page display
=> searchbar width

app/assets/stylesheets/components/_searchbar.scss, app/views/chats/list.html.erb, app/views/chats/list_by_user.html.erb, app/views/stareds/index.html.erb
added banner in every page
changed opacity of searchbar
=> banner all pages, searchbar opacity

app/views/stareds/index.html.erb
Now where stared message form is work good.
=> correct the stared message form

app/assets/stylesheets/pages/_home.scss, app/channels/application_cable/channel.rb, app/channels/application_cable/connection.rb, app/channels/presence_channel.rb, app/controllers/chats_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/users_controller.rb, app/javascript/application.js, app/javascript/channels/consumer.js, app/javascript/channels/index.js, app/javascript/channels/presence_channel.js, app/javascript/controllers/message_controller.js, app/models/user.rb, app/views/chats/_my_chats_online_users.html.erb, app/views/chats/index.html.erb, app/views/chats/list_by_user.html.erb, app/views/layouts/application.html.erb, config/environments/production.rb, config/importmap.rb, config/routes.rb, test/controllers/sessions_controller_test.rb
Finally, online users feature works..
=> now it works

app/assets/stylesheets/components/_chat.scss, app/controllers/stareds_controller.rb, app/views/chats/show.html.erb, app/views/messages/_message.html.erb
changed width of chats so it looks better on mobile screen
=> chat fixed
